# Generated by Django 4.2.7 on 2026-07-13 05:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('played', models.IntegerField(default=0)),
                ('won', models.IntegerField(default=0)),
                ('drawn', models.IntegerField(default=0)),
                ('lost', models.IntegerField(default=0)),
                ('goals_for', models.IntegerField(default=0)),
                ('goals_against', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('goal_difference', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-points', '-goal_difference', '-goals_for'],
            },
        ),
        migrations.CreateModel(
            name='MatchAward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('award_type', models.CharField(choices=[('man_of_match', 'Man of the Match'), ('best_player', 'Best Player'), ('best_defender', 'Best Defender'), ('best_goalkeeper', 'Best Goalkeeper'), ('emerging_player', 'Emerging Player')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentAward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('award_type', models.CharField(choices=[('top_scorer', 'Top Scorer'), ('top_assist', 'Top Assist'), ('best_player', 'Best Player'), ('best_defender', 'Best Defender'), ('best_goalkeeper', 'Best Goalkeeper'), ('emerging_player', 'Emerging Player'), ('fair_play', 'Fair Play Team')], max_length=20)),
            ],
        ),
    ]
