# Generated by Django 4.2.7 on 2026-07-13 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentaward',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.player'),
        ),
    ]
