# Generated by Django 4.2.7 on 2026-08-03 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fixtures', '0002_initial'),
        ('awards', '0002_initial'),
        ('teams', '0001_initial'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentaward',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_awards', to='tournaments.tournament'),
        ),
        migrations.AddField(
            model_name='matchaward',
            name='fixture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='fixtures.fixture'),
        ),
        migrations.AddField(
            model_name='matchaward',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.player'),
        ),
        migrations.AddField(
            model_name='leaguetable',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
        migrations.AddField(
            model_name='leaguetable',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentaward',
            unique_together={('tournament', 'award_type')},
        ),
    ]
