# Generated by Django 4.2.7 on 2026-07-17 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_initial'),
        ('awards', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchaward',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='matchaward',
            name='player_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='matchaward',
            name='award_type',
            field=models.CharField(choices=[('man_of_match', 'Man of the Match'), ('best_player', 'Best Player'), ('best_defender', 'Best Defender'), ('best_goalkeeper', 'Best Goalkeeper'), ('emerging_player', 'Emerging Player')], max_length=30),
        ),
        migrations.AlterField(
            model_name='matchaward',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.player'),
        ),
    ]
