# Generated by Django 4.2.7 on 2026-08-03 09:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('league', 'League'), ('group', 'Group'), ('group_a', 'Group A'), ('group_b', 'Group B'), ('group_c', 'Group C'), ('group_d', 'Group D'), ('group_e', 'Group E'), ('group_f', 'Group F'), ('group_g', 'Group G'), ('group_h', 'Group H'), ('round_of_64', 'Round of 64'), ('round_of_32', 'Round of 32'), ('round_of_16', 'Round of 16'), ('quarter', 'Quarter Final'), ('semi', 'Semi Final'), ('third_place', 'Third Place'), ('final', 'Final')], max_length=20)),
                ('match_date', models.DateField(blank=True, null=True)),
                ('match_time', models.TimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=255, null=True)),
                ('score_a', models.IntegerField(default=0)),
                ('score_b', models.IntegerField(default=0)),
                ('penalty_score_a', models.IntegerField(blank=True, null=True)),
                ('penalty_score_b', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('completed', 'Completed')], default='scheduled', max_length=20)),
                ('round_number', models.IntegerField(blank=True, null=True)),
                ('next_fixture_slot', models.CharField(blank=True, choices=[('a', 'Team A slot'), ('b', 'Team B slot')], max_length=1, null=True)),
                ('bracket_position', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('player_name', models.CharField(blank=True, max_length=100)),
                ('event_type', models.CharField(choices=[('goal', 'Goal'), ('assist', 'Assist'), ('yellow_card', 'Yellow Card'), ('red_card', 'Red Card')], max_length=20)),
                ('minute', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='fixtures.fixture')),
            ],
        ),
    ]
