# Generated by Django 4.2.7 on 2026-07-17 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_initial'),
        ('fixtures', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchevent',
            name='player_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='minute',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.player'),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.team'),
        ),
    ]
