# Generated by Django 4.2.7 on 2026-07-27 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0007_alter_fixture_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='bracket_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='next_fixture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeds_from', to='fixtures.fixture'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='next_fixture_slot',
            field=models.CharField(blank=True, choices=[('a', 'Team A slot'), ('b', 'Team B slot')], max_length=1, null=True),
        ),
    ]
