# Generated by Django 4.2.7 on 2026-07-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0008_fixture_bracket_position_fixture_next_fixture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='stage',
            field=models.CharField(choices=[('league', 'League'), ('group', 'Group'), ('group_a', 'Group A'), ('group_b', 'Group B'), ('group_c', 'Group C'), ('group_d', 'Group D'), ('group_e', 'Group E'), ('group_f', 'Group F'), ('group_g', 'Group G'), ('group_h', 'Group H'), ('round_of_64', 'Round of 64'), ('round_of_32', 'Round of 32'), ('round_of_16', 'Round of 16'), ('quarter', 'Quarter Final'), ('semi', 'Semi Final'), ('third_place', 'Third Place'), ('final', 'Final')], max_length=20),
        ),
    ]
