# Generated by Django 4.2.7 on 2026-08-03 09:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('area_name', models.CharField(blank=True, default='', max_length=200)),
                ('ground_type', models.CharField(choices=[('3s', '3-a-side'), ('5s', '5-a-side'), ('6s', '6-a-side'), ('7s', '7-a-side'), ('9s', '9-a-side'), ('11s', '11-a-side')], max_length=10)),
                ('age_category', models.CharField(choices=[('U7', 'Under 7'), ('U8', 'Under 8'), ('U9', 'Under 9'), ('U10', 'Under 10'), ('U11', 'Under 11'), ('U12', 'Under 12'), ('U13', 'Under 13'), ('U14', 'Under 14'), ('U15', 'Under 15'), ('U16', 'Under 16'), ('U17', 'Under 17'), ('U18', 'Under 18'), ('U19', 'Under 19'), ('U20', 'Under 20'), ('U21', 'Under 21'), ('U22', 'Under 22'), ('U23', 'Under 23'), ('Open', 'Open'), ('Veterans', 'Veterans (40+)')], max_length=10)),
                ('tournament_type', models.CharField(choices=[('league', 'League Only'), ('knockout', 'Knockout Only'), ('league_knockout', 'League + Knockout')], max_length=20)),
                ('home_and_away', models.BooleanField(default=False)),
                ('knockout_qualifiers', models.IntegerField(default=4)),
                ('max_teams', models.IntegerField(default=8)),
                ('third_place_option', models.BooleanField(default=False)),
                ('age_verification_required', models.BooleanField(default=False)),
                ('accept_aadhaar', models.BooleanField(default=False)),
                ('accept_school_certificate', models.BooleanField(default=False)),
                ('accept_birth_certificate', models.BooleanField(default=False)),
                ('public_stats', models.BooleanField(default=True)),
                ('is_private', models.BooleanField(default=False)),
                ('verification_link_token', models.CharField(blank=True, max_length=100, unique=True)),
                ('awards_config', models.JSONField(default=dict)),
                ('stats_config', models.JSONField(default=dict)),
                ('team_names_list', models.JSONField(blank=True, default=list)),
                ('fixture_generation_mode', models.CharField(choices=[('auto', 'Auto Generate'), ('manual', 'Manual Entry')], default='auto', max_length=10)),
                ('league_knockout_style', models.CharField(blank=True, choices=[('multi_group', 'Multi Group'), ('single_group', 'Single Group')], max_length=20, null=True)),
                ('num_groups', models.IntegerField(blank=True, default=4, null=True)),
                ('qualifiers_per_group', models.IntegerField(blank=True, default=2, null=True)),
                ('fixtures_generated', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('teams', models.ManyToManyField(blank=True, related_name='groups', to='teams.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='tournaments.tournament')),
            ],
        ),
    ]
