# Generated by Django 4.2.7 on 2026-07-13 05:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('ground_type', models.CharField(choices=[('3s', '3s'), ('5s', '5s'), ('6s', '6s'), ('7s', '7s'), ('11s', '11s')], max_length=5)),
                ('age_category', models.CharField(choices=[('U7', 'U7'), ('U8', 'U8'), ('U9', 'U9'), ('U10', 'U10'), ('U11', 'U11'), ('U12', 'U12'), ('U13', 'U13'), ('U14', 'U14'), ('U15', 'U15'), ('U16', 'U16'), ('U17', 'U17'), ('U18', 'U18'), ('U19', 'U19'), ('U20', 'U20'), ('U21', 'U21'), ('U22', 'U22'), ('U23', 'U23'), ('Open', 'Open')], max_length=5)),
                ('tournament_type', models.CharField(choices=[('league', 'League'), ('league_knockout', 'League + Knockout'), ('knockout', 'Knockout')], max_length=20)),
                ('age_verification_required', models.BooleanField(default=False)),
                ('verification_link_token', models.CharField(blank=True, max_length=255, unique=True)),
                ('awards_config', models.JSONField(default=dict)),
                ('public_stats', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
