# Generated by Django 4.2.7 on 2026-07-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='accept_aadhaar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='accept_birth_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='accept_school_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='area_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tournament',
            name='home_and_away',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='knockout_qualifiers',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='tournament',
            name='max_teams',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='tournament',
            name='stats_config',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='tournament',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='age_category',
            field=models.CharField(choices=[('U7', 'Under 7'), ('U8', 'Under 8'), ('U9', 'Under 9'), ('U10', 'Under 10'), ('U11', 'Under 11'), ('U12', 'Under 12'), ('U13', 'Under 13'), ('U14', 'Under 14'), ('U15', 'Under 15'), ('U16', 'Under 16'), ('U17', 'Under 17'), ('U18', 'Under 18'), ('U19', 'Under 19'), ('U20', 'Under 20'), ('U21', 'Under 21'), ('U22', 'Under 22'), ('U23', 'Under 23'), ('Open', 'Open'), ('Veterans', 'Veterans (40+)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='ground_type',
            field=models.CharField(choices=[('3s', '3-a-side'), ('5s', '5-a-side'), ('6s', '6-a-side'), ('7s', '7-a-side'), ('9s', '9-a-side'), ('11s', '11-a-side')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_type',
            field=models.CharField(choices=[('league', 'League Only'), ('knockout', 'Knockout Only'), ('league_knockout', 'League + Knockout')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='verification_link_token',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
