# Generated by Django 4.2.7 on 2026-07-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_tournament_accept_aadhaar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='fixture_generation_mode',
            field=models.CharField(choices=[('auto', 'Auto Generate'), ('manual', 'Manual Entry')], default='auto', max_length=10),
        ),
        migrations.AddField(
            model_name='tournament',
            name='league_knockout_style',
            field=models.CharField(blank=True, choices=[('multi_group', 'Multi Group'), ('single_group', 'Single Group')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='num_groups',
            field=models.IntegerField(blank=True, default=4, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='qualifiers_per_group',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='team_names_list',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
