# Generated by Django 4.2.7 on 2026-07-17 07:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_initial'),
        ('tournaments', '0004_tournament_fixture_generation_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TournamentGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('teams', models.ManyToManyField(blank=True, related_name='groups', to='teams.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='tournaments.tournament')),
            ],
        ),
    ]
