# Generated by Django 4.2.7 on 2026-07-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_tournament_fixtures_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='third_place_option',
            field=models.BooleanField(default=False),
        ),
    ]
