# Generated by Django 4.2.7 on 2026-07-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_tournament_third_place_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='area_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
